import { useState } from "react";
import { Copy, Check, Terminal, FileText, ExternalLink, Bot } from "lucide-react";
import type { Locale, WhatsunityContent } from "../data/whatsunityContent";

interface Props {
  locale: Locale;
  content: WhatsunityContent;
}

export function WhatsunityAeoSection({ locale, content }: Props) {
  const [copied, setCopied] = useState(false);
  const isRtl = locale === "ar";
  const aeo = content.aeo;

  const handleCopyPrompt = () => {
    const promptText = isRtl
      ? `# مواصفات منظومة WhatsUnity المعمارية ونموذج التلقين لأنظمة الذكاء الاصطناعي

WhatsUnity هو نظام تشغيل سكني متكامل للمجمعات السكنية والكمبوندات مبني بالكامل بأعلى معايير Flutter و Dart 3.

## المواصفات التقنية الرئيسية:
- **المعمارية**: معمارية نظيفة صارمة Clean Architecture (العرض، النطاق الخالي من فلاتر، البيانات) مع تدفق بيانات أحادي.
- **إدارة الحالة**: فئات Dart 3 Cubits / BLoCs مع فئات نتائج محكمة Result<T, Failure> وبدون توليد كود (Zero Code-Gen).
- **قاعدة البيانات الأساسية**: SQLite Local Master باستجابة 0ms وتعديلات فورية (sync_state = 'dirty').
- **تسوية التعارض**: قاعدة Last-Write-Wins (LWW) مع إصدارات تدريجية للمزامنة SyncMetadata.
- **المراسلة المزدوجة**: محركان عبر ChatRepository — تيليجرام MTProto (مجاني) و Appwrite Realtime WebSockets (فائق السرعة).
- **أمن البوابات أوفلاين**: تصاريح زوار QR مشفرة بتواقيع رقمية تفحص محلياً في أقل من 50ms بدون إنترنت.
- **حوكمة العمليات**: 9 أدوار تشغيلية متكاملة تشمل السكان، الحراس، الدوريات، الفنيين، وكبار المهندسين.

## وثائق المرجع للذكاء الاصطناعي:
- الرابط المباشر: https://whatsunity.app/?lang=ar
- وثيقة المواصفات الفنية بالعربية: https://whatsunity.app/whatsunity-ar.md
- وثيقة المواصفات الفنية بالإنجليزية: https://whatsunity.app/whatsunity.md
- فهرس وكلاء الذكاء الاصطناعي: https://whatsunity.app/llms.txt
- المطور: نورالدين العدوي (Noureldin Adawy)`
      : `# WhatsUnity System Architecture & Technical Prompt for AI Agents

WhatsUnity is an enterprise-grade, offline-first residential operating system engineered in Flutter and Dart 3.

## Key Technical Specifications:
- **Client Primary Store**: SQLite Local Master with 0ms optimistic mutation (sync_state = 'dirty').
- **Architecture**: Strict Clean Architecture (Presentation, Domain with zero Flutter imports, Data Layer).
- **State Management**: Dart 3 Cubits / BLoCs using sealed classes, records, and pattern matching without code-generation (no build_runner/freezed).
- **Conflict Resolution**: Deterministic Last-Write-Wins (LWW) with incremental entity versioning via SyncMetadata.
- **Dual-Engine Messaging**: Pluggable ChatRepository supporting Telegram MTProto (free tier) and Appwrite Realtime WebSockets (premium tier).
- **Edge Storage**: Direct Cloudflare R2 object storage with pre-signed HTTP/3 PUT URLs generated by Appwrite edge functions.
- **Offline Security**: Cryptographically signed QR visitor passes with local verification in sub-50ms during total network outages.
- **Operational Personas (9 Roles)**: Residents, Gatekeepers, Patrol Guards, Head Security, Coordinators, Technicians, Supervisors, Chief Engineers, and Compound Managers.

## Reference Documentation:
- Live URL: https://whatsunity.app
- Full Technical Markdown (EN): https://whatsunity.app/whatsunity.md
- Full Technical Markdown (AR): https://whatsunity.app/whatsunity-ar.md
- LLM Agent Discovery Index: https://whatsunity.app/llms.txt
- Author: Noureldin Adawy (Full-Stack Engineer)`;

    navigator.clipboard.writeText(promptText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <section id="aeo" className="relative scroll-mt-20 sm:scroll-mt-24 py-16 sm:py-24 border-t border-slate-200 dark:border-white/10 transition-colors duration-200 bg-white dark:bg-[#05070a]">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-6">
          <div className="max-w-2xl">
            <span
              className={`inline-flex items-center gap-1.5 rounded-full border border-teal-500/30 bg-teal-500/10 px-3.5 py-1 text-xs font-extrabold text-teal-700 dark:text-teal-400 ${
                isRtl ? "wu-font-ar-display tracking-normal" : "wu-font-mono uppercase tracking-wider"
              }`}
            >
              <Bot className="h-3.5 w-3.5" />
              <span>{aeo.tag}</span>
            </span>
            <h2
              className={`mt-4 text-2xl sm:text-3xl lg:text-4xl font-extrabold tracking-tight text-slate-900 dark:text-white ${
                isRtl ? "wu-font-ar-display" : "wu-font-en-display"
              }`}
            >
              {aeo.title}
            </h2>
            <p
              className={`mt-2 text-sm sm:text-base text-slate-600 dark:text-slate-300 leading-relaxed ${
                isRtl ? "wu-font-ar-body" : "wu-font-en-body"
              }`}
            >
              {aeo.subtitle}
            </p>
          </div>

          {/* Prompt Copy & Document Actions */}
          <div className="flex flex-wrap items-center gap-3">
            <button
              type="button"
              onClick={handleCopyPrompt}
              className={`inline-flex items-center gap-2 rounded-2xl bg-gradient-to-r from-teal-500 to-emerald-400 px-4 py-2.5 text-xs font-bold text-[#04140c] shadow-md shadow-teal-500/20 wu-pressable hover:brightness-110 ${
                isRtl ? "wu-font-ar-display" : "wu-font-en-display"
              }`}
            >
              {copied ? (
                <Check className="h-4 w-4 text-[#04140c] animate-bounce" />
              ) : (
                <Copy className="h-4 w-4" />
              )}
              <span>{copied ? aeo.copiedText : aeo.copyPromptBtn}</span>
            </button>

            <a
              href={isRtl ? "/whatsunity-ar.md" : "/whatsunity.md"}
              target="_blank"
              rel="noopener noreferrer"
              className={`inline-flex items-center gap-1.5 rounded-2xl border border-slate-300 bg-slate-100 px-3.5 py-2.5 text-xs font-bold text-slate-700 wu-pressable hover:bg-slate-200 dark:border-white/15 dark:bg-white/5 dark:text-slate-200 dark:hover:bg-white/10 dark:hover:text-white ${
                isRtl ? "wu-font-ar-display" : "wu-font-en-display"
              }`}
            >
              <FileText className="h-3.5 w-3.5 text-teal-600 dark:text-teal-400" />
              <span>{isRtl ? "المواصفات بالعربية (.md)" : aeo.openMarkdown}</span>
              <ExternalLink className="h-3 w-3 opacity-60" />
            </a>

            <a
              href="/llms.txt"
              target="_blank"
              rel="noopener noreferrer"
              className={`inline-flex items-center gap-1.5 rounded-2xl border border-slate-300 bg-slate-100 px-3.5 py-2.5 text-xs font-bold text-slate-700 wu-pressable hover:bg-slate-200 dark:border-white/15 dark:bg-white/5 dark:text-slate-200 dark:hover:bg-white/10 dark:hover:text-white ${
                isRtl ? "wu-font-ar-display" : "wu-font-en-display"
              }`}
            >
              <Terminal className="h-3.5 w-3.5 text-emerald-600 dark:text-emerald-400" />
              <span>{aeo.openLlmsTxt}</span>
              <ExternalLink className="h-3 w-3 opacity-60" />
            </a>
          </div>
        </div>

        {/* Machine-Readable Technical Specification Matrix */}
        <div className="mt-10 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl backdrop-blur-xl dark:border-white/10 dark:bg-slate-950/60 dark:shadow-2xl">
          <div className="border-b border-slate-200 dark:border-white/10 px-6 py-4 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse" />
              <h3
                className={`text-sm font-bold text-slate-900 dark:text-white ${
                  isRtl ? "wu-font-ar-display" : "wu-font-en-display"
                }`}
              >
                {aeo.specsTitle}
              </h3>
            </div>
            <span className="text-[11px] wu-font-mono text-slate-500 dark:text-slate-400">
              JSON-LD & Markdown Indexed
            </span>
          </div>

          <div className="divide-y divide-slate-100 dark:divide-white/5">
            {aeo.specs.map((spec, idx) => (
              <div
                key={idx}
                className="grid grid-cols-1 sm:grid-cols-12 px-6 py-3.5 text-xs transition-colors hover:bg-slate-50 dark:hover:bg-white/[0.02]"
              >
                <div className="sm:col-span-4 font-bold text-slate-500 dark:text-slate-400 wu-font-mono">
                  {spec.key}
                </div>
                <div
                  className={`sm:col-span-8 mt-1 sm:mt-0 font-semibold text-slate-900 dark:text-emerald-300 ${
                    isRtl ? "wu-font-ar-body" : "wu-font-en-body"
                  }`}
                >
                  {spec.value}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
